receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: "0.0.0.0:55680"
    insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

